---
- hosts: rnb
  become: True
  tasks:
    - name: Run commands
      commands: "docker stop raa043/httpd_project:latest"
      commands: "docker rm -f raam043/httpd_project:latest"
      commands: "docker image rm -f raam043/httpd_project:latest"
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/httpd_project:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
