---
- name: Install Docker on Amazon linux
  hosts: rnb
  become: True
  tasks:
     - name: Installing packages
       command: "yum update -y"
       command: "pip3 install docker-py"
       command: "pip install ‘docker==4.4.4"
     - name: Install Docker
       yum:
        name: docker
        state: latest

     - name: Start & Enable docker
       systemd:
         name: docker
         state: started
         enabled: yes
