- hosts: rnb
  become: True
  tasks:
  - name: Docker
    command: "yum install docker -y"
    command: "systemctl enable docker"
    command: "systemctl start docker"
    command: "yum install pip -y"
    command: "pip install docker-py"
