---
- name: Install Docker on Amazon linux
  hosts: rnb
  become: True
  tasks:

     - name: Install Docker
       yum:
        name: docker
        state: latest

     - name: Start & Enable docker
       systemd:
         name: docker
         state: started
         enabled: yes

     - name: Installing pip
       command: "yum install pip -y"

     - name:  Installing pip3
       command: "pip3 install docker-py"
