---
- name: Install Docker on Amazon linux
  hosts: rnb
  become: True
  tasks:
     - name: Installing packages
       yum_repository:
         name: docker
         description: repo for docker
         baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
         gpgcheck: no

     - name: Installing docker
       command: "yum install docker -y"
       command: "yum install pip -y"

     - name: Starting and enabling docker service
       service:
         name: docker
         state: started
         enabled: yes

     - name: install python3
       package:
         name: python3
         state: present

     - name: conf pip for docker
       pip:
         name: docker-py
