---
- hosts: rnb
  become: True
  tasks:
    - name: webpage directory
      copy:
        src: index.html
        dest: "/usr/local/apache2/htdocs"
    - name: Pull httpd docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull
    - name: docker rename
      command: "docker tag httpd:latest raam043/httpd_project:v2"
