---
- hosts: rnb
  become: True
  tasks:    
    - name: Pull httpd docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull

    - name: Coping website to httpd
      copy:
        src: ./index.html
        dest: /usr/local/apache2/htdocs
