---
- hosts: rnb
  become: True
  tasks:
    - name: Installing pip
      command: "pip3 install docker-py"
      
    - name: Pull httpd docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull

    - name: Coping website to httpd
      copy:
        src: ./index.html
        dest: /usr/local/apache2/htdocs
