---
- hosts: rnb
  become: True
  tasks:
    - name: webpage directory
      file:
        state: directory
        dest: "/root/webpage"
    - name: Pull httpd docker image
      docker_image:
        name: httpd:latest
        tag: latest
        source: pull

    - name: Copy website to the host
      copy:
        src: ./index.html
        dest: /root/webpage
