---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/httpdimage:latest
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
        volumes:
        - /root/webpage/:/usr/local/apache2/htdocs/
