---
- hosts: rnb
  become: True
  tasks:
    - name: webpage directory
      file:
        state: directory
        dest: "/root/webpage"
    - name: Pull httpd docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull
