---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/httpd_project:${BUILD_NUMBER}
        state: started
        exposed_ports:
        - "80"
        ports:
        - "80:80"
        volumes:
        - :/usr/local/apache2/htdocs/
