---
- hosts: rnb
  become: True
  tasks:

    - name: Pull httpd docker image
      docker_image:
        name: httpd
        tag: latest
        source: pull
    - name: docker rename
      command: "docker tag httpd:latest raam043/httpd_project:v2"
    - name: webpage directory
      command: cp index.html /usr/local/apache2/htdocs
