---
- hosts: rnb
  become: True
  tasks:
    - name: webpage directory
      file:
        state: directory
        dest: "/root/webpage"
    - name: Pull nginx docker image
      docker_image:
        name: nginx
        tag: latest
        source: pull
    - name: docker rename
      command: "docker tag nginx:latest raam043/nginx_project:latest"
    - name: Copy website to the host
      copy:
        src: ./index.html
        dest: /root/webpage
