---
- hosts: rnb
  become: True
  tasks:
  
    - name: Run docker container
      docker_container:
        name: WebServer
        image: raam043/tomcat:latest
        state: started
        exposed_ports:
        - "8080"
        ports:
        - "8080:8080"
        volumes:
        - /root/webpage/:/usr/local/tomcat/webapps
