---
- hosts: rnb
  become: True
  tasks:
    - name: webpage directory
      file:
        state: directory
        dest: "/root/webpage"
    - name: Pull httpd docker image
      docker_image:
        name: tomcat
        tag: latest
        source: pull
    - name: docker rename
      command: "docker tag tomcat:latest raam043/tomcat:latest"
    - name: Copy website to the host
      copy:
        src: ./index.html
        dest: /root/webpage
